[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
dex_raise = "BTorkvs6ZfddcEqcZqqd9EAT8thUBB2gE1ikmLH7m8i4"

[programs.devnet]
dex_raise = "6h6tptXmE1g9F6pez3yaZYxdvdkBQRFnw3VH1Fcs3uze"

[programs.mainnet]
dex_raise = "6h6tptXmE1g9F6pez3yaZYxdvdkBQRFnw3VH1Fcs3uze"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "mainnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
